import type { MenuItem, Canteen } from "./types"

export const mockCanteens: Canteen[] = [
  {
    id: "canteen-1",
    name: "Main Campus Canteen",
    location: "Building A, Ground Floor",
    isOpen: true,
    openTime: "07:00",
    closeTime: "20:00",
  },
  {
    id: "canteen-2",
    name: "Engineering Block Cafe",
    location: "Engineering Block, 1st Floor",
    isOpen: true,
    openTime: "08:00",
    closeTime: "18:00",
  },
]

export const mockMenuItems: MenuItem[] = [
  {
    id: "item-1",
    name: "Masala Dosa",
    description: "Crispy rice crepe filled with spiced potato filling, served with sambar and chutney",
    price: 60,
    category: "Breakfast",
    image: "/masala-dosa.png",
    available: true,
    prepTime: 10,
    canteenId: "canteen-1",
  },
  {
    id: "item-2",
    name: "Veg Thali",
    description: "Complete meal with dal, sabzi, roti, rice, salad, and dessert",
    price: 120,
    category: "Lunch",
    image: "/indian-thali.jpg",
    available: true,
    prepTime: 15,
    canteenId: "canteen-1",
  },
  {
    id: "item-3",
    name: "Paneer Butter Masala",
    description: "Cottage cheese cubes in rich tomato and butter gravy with naan",
    price: 140,
    category: "Dinner",
    image: "/paneer-butter-masala.png",
    available: true,
    prepTime: 12,
    canteenId: "canteen-1",
  },
  {
    id: "item-4",
    name: "Samosa",
    description: "Crispy fried pastry filled with spiced potatoes and peas",
    price: 20,
    category: "Snacks",
    image: "/crispy-golden-samosas.png",
    available: true,
    prepTime: 5,
    canteenId: "canteen-1",
  },
  {
    id: "item-5",
    name: "Chai",
    description: "Hot Indian tea with milk and spices",
    price: 15,
    category: "Beverages",
    image: "/indian-chai-tea.jpg",
    available: true,
    prepTime: 3,
    canteenId: "canteen-1",
  },
  {
    id: "item-6",
    name: "Chole Bhature",
    description: "Spicy chickpea curry with fluffy fried bread",
    price: 80,
    category: "Breakfast",
    image: "/chole-bhature.jpg",
    available: true,
    prepTime: 12,
    canteenId: "canteen-1",
  },
  {
    id: "item-7",
    name: "Biryani",
    description: "Fragrant basmati rice with vegetables and aromatic spices",
    price: 100,
    category: "Lunch",
    image: "/vegetable-biryani.png",
    available: true,
    prepTime: 20,
    canteenId: "canteen-2",
  },
  {
    id: "item-8",
    name: "Pasta",
    description: "Italian pasta in white sauce with vegetables",
    price: 90,
    category: "Dinner",
    image: "/white-sauce-pasta.jpg",
    available: false,
    prepTime: 15,
    canteenId: "canteen-2",
  },
  {
    id: "item-9",
    name: "Sandwich",
    description: "Grilled vegetable sandwich with cheese",
    price: 50,
    category: "Snacks",
    image: "/grilled-sandwich.png",
    available: true,
    prepTime: 8,
    canteenId: "canteen-2",
  },
  {
    id: "item-10",
    name: "Cold Coffee",
    description: "Chilled coffee with milk and ice cream",
    price: 60,
    category: "Beverages",
    image: "/cold-coffee.png",
    available: true,
    prepTime: 5,
    canteenId: "canteen-2",
  },
]
